repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: ./helm/kube-prometheus-stack
    values:
      - values/kube-prometheus-stack-values.yaml

  - name: k6-operator
    namespace: k6
    chart: ./helm/k6-operator
    values:
      - values/k6-operator-values.yaml

helmDefaults:
  createNamespace: true
