apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-example
spec:
  selector:
    matchLabels:
      app: nginx-with-pdb
  minAvailable: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-pdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-with-pdb
  template:
    metadata:
      labels:
        app: nginx-with-pdb
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
