apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-pod-prestop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-with-pod-prestop
  template:
    metadata:
      labels:
        app: nginx-with-pod-prestop
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo 'Pod is going to be terminated' && sleep 10"]
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 3
