kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: 3z-6n
nodes:
- role: control-plane
  image: kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027
  extraMounts:
    - hostPath: /home/username/.docker/config.json
      containerPath: /var/lib/kubelet/config.json
      readOnly: true
- role: worker
  image: kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          register-with-taints: "gpu=true:NoSchedule"
          node-labels: "zone=a"
  extraMounts:
    - hostPath: /home/username/.docker/config.json
      containerPath: /var/lib/kubelet/config.json
      readOnly: true
- role: worker
  image: kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          register-with-taints: "gpu=true:NoSchedule"
          node-labels: "zone=b"
  extraMounts:
    - hostPath: /home/username/.docker/config.json
      containerPath: /var/lib/kubelet/config.json
      readOnly: true
- role: worker
  image: kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          register-with-taints: "gpu=true:NoSchedule"
          node-labels: "zone=c"
  extraMounts:
    - hostPath: /home/username/.docker/config.json
      containerPath: /var/lib/kubelet/config.json
      readOnly: true
- role: worker
  image: kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "zone=a"
  extraMounts:
    - hostPath: /home/username/.docker/config.json
      containerPath: /var/lib/kubelet/config.json
      readOnly: true
- role: worker
  image: kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "zone=b"
  extraMounts:
    - hostPath: /home/username/.docker/config.json
      containerPath: /var/lib/kubelet/config.json
      readOnly: true
- role: worker
  image: kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "zone=c"
  extraMounts:
    - hostPath: /home/username/.docker/config.json
      containerPath: /var/lib/kubelet/config.json
      readOnly: true
